name: CI build

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  CIBW:
    uses: lukeparser/lukeparser/.github/workflows/cibuildwheel.yml@dev-cibw
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
