name: PyTest

on:
  pull_request:
    paths:
      - 'src/luke/parser/*'

jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/pytest
