name: PyTest

on:
  push:
    paths:
      - 'src/luke/parser/*'
  pull_request:
    paths:
      - 'src/luke/parser/*'

jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: cclauss/GitHub-Action-for-pytest@0.5.0
      with:
          args: "pip install -r requirements.txt; pytest -v tests"
