name: Test build

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  CIBW:
    uses: lukeparser/lukeparser/.github/workflows/cibuildwheel.yml@master
    with:
      fail-fast: true
      deploy: false
